/* Future (futuro): reference tables and quiz sentences.
   Latin American Spanish: the plural “you” is ustedes, which takes the ellos form.
   In tables, [square brackets] mark the part of the form to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap. */

const FUTURE_TENSE = {
  id: 'future', pl: 'Futuro', en: 'Future',
  intro: 'Spanish has two everyday futures. Ir a + infinitivo (voy a comer) is the spoken favourite for plans and things about to happen. The futuro simple (comeré) adds -é, -ás, -á to the whole infinitive and is used for predictions, promises and guesses about the present. In Latin America “you” in the plural is ustedes, which takes the ellos form.',

  groups: [
    {
      id: 'future-ir-a', pl: 'Ir a + verbo', en: 'Going to', q: 'voy a comer',
      summary: 'The present of ir, then a, then the infinitive: voy a comer. This is the most common way to talk about plans and things about to happen, especially in speech.',
      tables: [
        { title: 'ir in the present + a + infinitive',
          cols: [{ label: 'ir', tint: 'all' }, { label: 'a + infinitive', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[voy]', 'a comer'] },
            { who: 'tú', cells: ['[vas]', 'a comer'] },
            { who: 'él / ella / usted', cells: ['[va]', 'a comer'] },
            { who: 'nosotros', cells: ['[vamos]', 'a comer'] },
            { who: 'ellos / ellas / ustedes', cells: ['[van]', 'a comer'] },
          ] },
        { title: 'Where the pronoun goes',
          cols: [{ label: 'Before ir', tint: 'all' }, { label: 'Attached to the infinitive', tint: 'all' }],
          rows: [
            { who: 'levantarse', cells: ['[me] voy a levantar', 'voy a levantar[me]'] },
            { who: 'comprarlo', cells: ['[lo] voy a comprar', 'voy a comprar[lo]'] },
            { who: 'llamarte', cells: ['[te] voy a llamar', 'voy a llamar[te]'] },
          ] },
        { title: 'Signal words for the near future',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'mañana', cells: ['Mañana voy a trabajar desde casa.', 'Tomorrow I am going to work from home.'] },
            { who: 'esta tarde', cells: ['Esta tarde vamos a ir al cine.', 'This afternoon we are going to the cinema.'] },
            { who: 'este fin de semana', cells: ['Este fin de semana va a llover.', 'This weekend it is going to rain.'] },
            { who: 'la próxima semana', cells: ['La próxima semana van a venir mis padres.', 'Next week my parents are coming.'] },
            { who: 'dentro de una hora', cells: ['Dentro de una hora va a salir el tren.', 'The train is leaving in an hour.'] },
            { who: 'luego, pronto', cells: ['Luego te voy a llamar.', 'I will call you later.'] },
          ] },
      ],
      rules: [
        { t: 'Plans and intentions', ex: 'Este verano vamos a viajar a Perú.', en: 'This summer we are going to travel to Peru.' },
        { t: 'Something about to happen, with evidence now', ex: 'Mira el cielo, va a llover.', en: 'Look at the sky, it is going to rain.' },
        { t: 'Reflexive and object pronouns go before ir or attach to the infinitive', ex: 'Me voy a bañar. Voy a bañarme.', en: 'I am going to have a shower.' },
        { t: 'The plain present also works for fixed plans, as in English', ex: 'Mañana tengo una reunión.', en: 'Tomorrow I have a meeting.' },
      ],
      watch: [
        'Do not drop the a: “voy comer” is wrong. Voy a comer.',
        'Vamos a + infinitive can also mean “let’s”: ¡Vamos a bailar!',
        'Va and vamos have no accent, and va has no h. Compare ha comido (has eaten) with va a comer (is going to eat).',
        'Ustedes takes van: ¿Ustedes van a venir?',
      ],
    },
    {
      id: 'future-reg', pl: 'Futuro regular', en: 'Simple future, regular', q: 'hablar → hablaré',
      summary: 'The futuro simple adds one set of endings to the whole infinitive, for all three conjugations: -é, -ás, -á, -emos, -án. It is used for predictions, promises and the more distant or less certain future.',
      tables: [
        { title: 'hablar, comer, vivir: one set of endings',
          cols: [{ label: '-ar', tint: 'all' }, { label: '-er', tint: 'all' }, { label: '-ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['hablar[é]', 'comer[é]', 'vivir[é]'] },
            { who: 'tú', cells: ['hablar[ás]', 'comer[ás]', 'vivir[ás]'] },
            { who: 'él / ella / usted', cells: ['hablar[á]', 'comer[á]', 'vivir[á]'] },
            { who: 'nosotros', cells: ['hablar[emos]', 'comer[emos]', 'vivir[emos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['hablar[án]', 'comer[án]', 'vivir[án]'] },
          ] },
        { title: 'Regular even though the present is not',
          cols: [{ label: 'present', tint: 'all' }, { label: 'futuro', tint: 'all' }],
          rows: [
            { who: 'ser', cells: ['soy', 'ser[é]'] },
            { who: 'ir', cells: ['voy', 'ir[é]'] },
            { who: 'estar', cells: ['estoy', 'estar[é]'] },
            { who: 'volver', cells: ['vuelvo', 'volver[é]'] },
            { who: 'empezar', cells: ['empiezo', 'empezar[é]'] },
            { who: 'dormir', cells: ['duermo', 'dormir[é]'] },
          ] },
        { title: 'Signal words',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'el próximo año', cells: ['El próximo año viviré en Lima.', 'Next year I will live in Lima.'] },
            { who: 'dentro de diez años', cells: ['Dentro de diez años seremos ricos.', 'In ten years we will be rich.'] },
            { who: 'algún día', cells: ['Algún día visitaré Japón.', 'One day I will visit Japan.'] },
            { who: 'en el futuro', cells: ['En el futuro trabajaremos menos.', 'In the future we will work less.'] },
            { who: 'seguro que', cells: ['Seguro que llegará tarde.', 'He will be late for sure.'] },
          ] },
      ],
      rules: [
        { t: 'Predictions and expectations', ex: 'Mañana lloverá en el norte.', en: 'Tomorrow it will rain in the north.' },
        { t: 'Promises', ex: 'Te llamaré esta noche.', en: 'I will call you tonight.' },
        { t: 'The endings go on the whole infinitive, including the -ar, -er or -ir', ex: 'Viviremos cerca del mar.', en: 'We will live near the sea.' },
        { t: 'Every form except nosotros has an accent', ex: 'Comerás, comerá, comerán.', en: 'You will eat, he will eat, they will eat.' },
      ],
      watch: [
        'Do not cut the infinitive: comeré, not “comé”; viviré, not “vivé”.',
        'Nosotros is the only form without an accent: hablaremos.',
        'Ser and ir are regular here: seré, iré. Their irregularity belongs to the past tenses.',
        'After cuando with a future meaning Spanish uses the subjunctive: cuando llegue, te llamaré, never “cuando llegaré”.',
        'Ustedes takes the ellos form, -án: ustedes hablarán, ustedes comerán.',
      ],
    },
    {
      id: 'future-irr', pl: 'Futuro irregular', en: 'Simple future, irregular', q: 'tener → tendré, hacer → haré',
      summary: 'Twelve common verbs shorten their infinitive before the same endings: tendr-, podr-, har-, dir-. The endings never change, only the stem does.',
      tables: [
        { title: 'tener, hacer, decir: short stem, same endings',
          cols: [{ label: 'tener', tint: 'all' }, { label: 'hacer', tint: 'all' }, { label: 'decir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[tendr]é', '[har]é', '[dir]é'] },
            { who: 'tú', cells: ['[tendr]ás', '[har]ás', '[dir]ás'] },
            { who: 'él / ella / usted', cells: ['[tendr]á', '[har]á', '[dir]á'] },
            { who: 'nosotros', cells: ['[tendr]emos', '[har]emos', '[dir]emos'] },
            { who: 'ellos / ellas / ustedes', cells: ['[tendr]án', '[har]án', '[dir]án'] },
          ] },
        { title: 'The twelve stems in three patterns',
          cols: [{ label: 'stem', tint: 'all' }, { label: 'yo', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'drop the e: poder', cells: ['podr-', '[podr]é', '[podr]án'] },
            { who: 'saber', cells: ['sabr-', '[sabr]é', '[sabr]án'] },
            { who: 'querer', cells: ['querr-', '[querr]é', '[querr]án'] },
            { who: 'haber', cells: ['habr-', '[habr]é', '[habr]án'] },
            { who: 'caber', cells: ['cabr-', '[cabr]é', '[cabr]án'] },
            { who: 'vowel becomes d: tener', cells: ['tendr-', '[tendr]é', '[tendr]án'] },
            { who: 'poner', cells: ['pondr-', '[pondr]é', '[pondr]án'] },
            { who: 'salir', cells: ['saldr-', '[saldr]é', '[saldr]án'] },
            { who: 'venir', cells: ['vendr-', '[vendr]é', '[vendr]án'] },
            { who: 'valer', cells: ['valdr-', '[valdr]é', '[valdr]án'] },
            { who: 'shortened: hacer', cells: ['har-', '[har]é', '[har]án'] },
            { who: 'decir', cells: ['dir-', '[dir]é', '[dir]án'] },
          ] },
      ],
      rules: [
        { t: 'Poder, saber, querer, haber and caber drop the e of the infinitive', ex: 'No podré ir mañana.', en: 'I will not be able to go tomorrow.' },
        { t: 'Tener, poner, salir, venir and valer replace the vowel with d', ex: 'Tendremos tiempo el domingo.', en: 'We will have time on Sunday.' },
        { t: 'Hacer and decir shrink to har- and dir-', ex: 'Te diré la verdad.', en: 'I will tell you the truth.' },
        { t: 'Compounds follow the base verb: mantener, suponer, deshacer', ex: 'Supongo que mantendrá su promesa.', en: 'I suppose he will keep his promise.' },
        { t: 'Hay in the future is habrá, one form for singular and plural', ex: 'Mañana habrá una fiesta.', en: 'Tomorrow there will be a party.' },
      ],
      watch: [
        'Querer doubles the r: querré, querrá. Do not write “quereré”.',
        'The endings stay the same: tendré, tendrás, tendrá. Only the stem is short.',
        'Ser and ir look like candidates but are regular in the future: seré, iré.',
        'Habrá never changes: habrá un problema, habrá problemas.',
        'Ustedes takes the ellos form: ustedes tendrán, ustedes harán.',
      ],
    },
    {
      id: 'future-prob', pl: 'Probabilidad', en: 'Guessing and future perfect', q: 'Serán las tres. Habrá salido.',
      summary: 'The futuro also expresses a guess about the present: ¿Dónde estará Juan? means I wonder where Juan is. The futuro perfecto (habré + participle) says what will have happened by a point in the future, or guesses about the recent past: habrá salido ya.',
      tables: [
        { title: 'The future as a guess',
          cols: [{ label: 'Spanish', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'about the time', cells: ['[Serán] las tres.', 'It must be about three.'] },
            { who: 'about a person', cells: ['[Tendrá] unos cuarenta años.', 'He must be about forty.'] },
            { who: 'a question', cells: ['¿Dónde [estarán] mis llaves?', 'Where can my keys be?'] },
            { who: 'about the recent past', cells: ['[Habrá perdido] el autobús.', 'She must have missed the bus.'] },
          ] },
        { title: 'futuro perfecto: habré + participle',
          cols: [{ label: 'haber', tint: 'all' }, { label: 'participle', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[habré]', 'terminado, comido, salido'] },
            { who: 'tú', cells: ['[habrás]', 'terminado, comido, salido'] },
            { who: 'él / ella / usted', cells: ['[habrá]', 'terminado, comido, salido'] },
            { who: 'nosotros', cells: ['[habremos]', 'terminado, comido, salido'] },
            { who: 'ellos / ellas / ustedes', cells: ['[habrán]', 'terminado, comido, salido'] },
          ] },
      ],
      rules: [
        { t: 'A guess or estimate about now: the futuro simple', ex: 'Serán las diez.', en: 'It must be about ten.' },
        { t: 'A guess about what has already happened: the futuro perfecto', ex: 'No contesta. Se habrá dormido.', en: 'She is not answering. She must have fallen asleep.' },
        { t: 'Something that will be finished by a point in the future, often with para or antes de', ex: 'Para el viernes habremos terminado el trabajo.', en: 'By Friday we will have finished the work.' },
        { t: 'Questions in the futuro mean “I wonder”', ex: '¿Quién será a estas horas?', en: 'Who can that be at this hour?' },
      ],
      watch: [
        'Context decides: tendrá veinte años is a guess about now, not a prediction, when you are looking at someone.',
        'The participle never changes, and the irregular ones are the same as in the perfecto: habrá hecho, habrá dicho.',
        'English adds “must” or “probably”; Spanish adds nothing, the tense does the job.',
      ],
    },
    {
      id: 'future-choice', pl: 'Ir a o futuro', en: 'Going to or will', q: 'voy a comer / comeré',
      summary: 'Both forms talk about the future, and often either works. Ir a is the natural choice for plans, decisions already made and things about to happen; the futuro simple suits predictions, promises, the distant future and formal or written Spanish.',
      tables: [
        { title: 'Which one?',
          cols: [{ label: 'ir a + infinitive', tint: 'all' }, { label: 'futuro simple', tint: 'all' }],
          rows: [
            { who: 'Typical use', cells: ['plan, intention, decision already made, something about to happen', 'prediction, promise, guess about now, distant future'] },
            { who: 'Example', cells: ['Esta tarde voy a estudiar.', 'Algún día seré médico.'] },
            { who: 'English', cells: ['This afternoon I am going to study.', 'One day I will be a doctor.'] },
            { who: 'Register', cells: ['spoken, informal', 'written, formal, also spoken'] },
          ] },
        { title: 'Often both are fine',
          cols: [{ label: 'ir a', tint: 'all' }, { label: 'futuro', tint: 'all' }],
          rows: [
            { who: 'prediction', cells: ['Mañana va a llover.', 'Mañana lloverá.'] },
            { who: 'plan', cells: ['Nos vamos a mudar.', 'Nos mudaremos.'] },
            { who: 'promise', cells: ['Te lo voy a devolver.', 'Te lo devolveré.'] },
            { who: 'guess about now', cells: ['—', 'Serán las cinco.'] },
            { who: 'evidence in front of you', cells: ['¡Se va a caer!', '—'] },
          ] },
      ],
      rules: [
        { t: 'A plan or decision already made: ir a', ex: 'Este año voy a aprender a manejar.', en: 'This year I am going to learn to drive.' },
        { t: 'Evidence you can see now: ir a', ex: 'Cuidado, el vaso se va a caer.', en: 'Careful, the glass is going to fall.' },
        { t: 'A promise: futuro simple, or ir a in relaxed speech', ex: 'No te preocupes, yo lo haré.', en: 'Don’t worry, I will do it.' },
        { t: 'The distant or uncertain future and formal predictions: futuro simple', ex: 'En 2050 la gente vivirá cien años.', en: 'In 2050 people will live to a hundred.' },
        { t: 'A guess about the present: only the futuro simple', ex: 'Serán las cinco.', en: 'It must be about five.' },
      ],
      watch: [
        'In speech ir a wins for anything already planned. The futuro simple can sound formal, or like a prophecy.',
        'Van a ser las cinco is not a guess: it means the clock is about to strike five.',
        'Voy a ir is fine; iré is a shorter option with the same meaning.',
      ],
    },
  ],

  sentences: [
    // Ir a + infinitivo
    { c: 'future-ir-a', s: 'Mañana{tomorrow} ___ a{(personal a)} mis{my|m.pl} abuelos{grandparents|m.pl}.', base: 'visitar', hint: 'yo', gloss: 'to visit', a: ['voy a visitar'], p: 'yo', en: 'Tomorrow I am going to visit my grandparents.', why: 'A plan for tomorrow: voy a plus the infinitive.' },
    { c: 'future-ir-a', s: 'Esta{this|f} noche{night|f} ___ en{at} un{a|m} restaurante{restaurant|m} italiano{Italian|m}.', base: 'cenar', hint: 'nosotros', gloss: 'to have dinner', a: ['vamos a cenar'], p: 'nosotros', en: 'Tonight we are going to have dinner at an Italian restaurant.', why: 'A plan for tonight: vamos a cenar. Vamos has no accent.' },
    { c: 'future-ir-a', s: '¿Qué{what} ___ este{this|m} fin_de_semana{weekend|m}?', base: 'hacer', hint: 'tú', gloss: 'to do', a: ['vas a hacer'], p: 'tú', en: 'What are you going to do this weekend?', why: 'Asking about plans: vas a hacer.' },
    { c: 'future-ir-a', s: 'Mira{look} esas{those|f.pl} nubes{cloud|f.pl}, ___.', base: 'llover', hint: 'it', gloss: 'to rain', a: ['va a llover'], p: 'él', en: 'Look at those clouds, it is going to rain.', why: 'Evidence now for something about to happen: va a llover.' },
    { c: 'future-ir-a', s: 'Mis{my|m.pl} padres{parents|m.pl} ___ una{a|f} casa{house|f} en{in} el{the|m} pueblo{village|m}.', base: 'comprar', gloss: 'to buy', a: ['van a comprar'], p: 'ellos', en: 'My parents are going to buy a house in the village.', why: 'A plan already made: van a comprar.' },
    { c: 'future-ir-a', s: '¿Ustedes{you (plural)} ___ a{to} la{the|f} fiesta{party|f} de{of} Ana{Ana}?', base: 'ir', gloss: 'to go', a: ['van a ir'], p: 'ellos', en: 'Are you going to go to Ana’s party?', why: 'Ir a ir is fine and common: van a ir. Ustedes takes the ellos form, van.' },
    { c: 'future-ir-a', s: 'La_próxima_semana{next week|f} mi{my|f} hermana{sister|f} ___ a{to} trabajar{work} en{in} Londres{London}.', base: 'empezar', gloss: 'to start', a: ['va a empezar'], p: 'él', en: 'Next week my sister is going to start working in London.', why: 'A fixed plan in the near future: va a empezar. The second a belongs to empezar a + infinitive.' },
    { c: 'future-ir-a', s: '___ temprano{early} porque{because} tengo{I have} un{a|m} examen{exam|m}.', base: 'acostarse', hint: 'yo', gloss: 'to go to bed', a: ['Me voy a acostar', 'Voy a acostarme'], p: 'yo', en: 'I am going to go to bed early because I have an exam.', why: 'The reflexive pronoun goes before voy or attaches to the infinitive: me voy a acostar, voy a acostarme.' },
    { c: 'future-ir-a', s: 'Dentro_de{in} una{an|f} hora{hour|f} ___ el{the|m} tren{train|m}.', base: 'salir', gloss: 'to leave', a: ['va a salir'], p: 'él', en: 'The train is going to leave in an hour.', why: 'Something about to happen at a set time: va a salir.' },
    { c: 'future-ir-a', s: 'Este{this|m} verano{summer|m} ustedes{you (plural)} ___ inglés{English|m} en{in} Canadá{Canada}.', base: 'estudiar', gloss: 'to study', a: ['van a estudiar'], p: 'ellos', en: 'This summer you are going to study English in Canada.', why: 'A plan for the summer. Ustedes takes the ellos form: van a estudiar.' },
    { c: 'future-ir-a', s: 'No{not} ___ más{any more} café{coffee|m}, me{me} pone{makes} nervioso{nervous|m}.', base: 'tomar', hint: 'yo', gloss: 'to have (food, drink)', a: ['voy a tomar'], p: 'yo', en: 'I am not going to have any more coffee, it makes me nervous.', why: 'An intention or decision: no voy a tomar.' },
    { c: 'future-ir-a', s: 'Luego{later} ___ a{(personal a)} Pablo{Pablo} para{to} invitarlo{invite him}.', base: 'llamar', hint: 'nosotros', gloss: 'to call', a: ['vamos a llamar'], p: 'nosotros', en: 'Later we are going to call Pablo to invite him.', why: 'Luego points to the near future: vamos a llamar.' },
    { c: 'future-ir-a', s: '¿A_qué_hora{what time} ___ los{the|m.pl} invitados{guest|m.pl}?', base: 'llegar', gloss: 'to arrive', a: ['van a llegar'], p: 'ellos', en: 'What time are the guests going to arrive?', why: 'Los invitados is ellos: van a llegar.' },
    { c: 'future-ir-a', s: 'Mi{my|m} hermano{brother|m} ___ mañana{tomorrow} muy{very} temprano{early}.', base: 'levantarse', gloss: 'to get up', a: ['se va a levantar', 'va a levantarse'], p: 'él', en: 'My brother is going to get up very early tomorrow.', why: 'Both positions of the pronoun are fine: se va a levantar, va a levantarse.' },
    { c: 'future-ir-a', s: '¡Cuidado{careful}, ___!', base: 'caerse', hint: 'tú', gloss: 'to fall', a: ['te vas a caer', 'vas a caerte'], p: 'tú', en: 'Careful, you are going to fall!', why: 'Something about to happen right now: te vas a caer.' },

    // Futuro regular
    { c: 'future-reg', s: 'Mañana{tomorrow} te{you} ___ por{in} la{the|f} tarde{afternoon|f}.', base: 'llamar', hint: 'yo', gloss: 'to call', a: ['llamaré'], p: 'yo', en: 'Tomorrow I will call you in the afternoon.', why: 'A promise: futuro simple. Yo takes -é on the whole infinitive: llamaré.' },
    { c: 'future-reg', s: 'El_próximo_año{next year|m} mis{my|m.pl} padres{parents|m.pl} ___ a{to} Perú{Peru}.', base: 'viajar', gloss: 'to travel', a: ['viajarán'], p: 'ellos', en: 'Next year my parents will travel to Peru.', why: 'Ellos takes -án: viajarán, with an accent.' },
    { c: 'future-reg', s: '¿Dónde{where} ___ dentro_de{in} diez{ten} años{year|m.pl}?', base: 'vivir', hint: 'tú', gloss: 'to live', a: ['vivirás'], p: 'tú', en: 'Where will you live in ten years?', why: 'The distant future: futuro simple. Tú takes -ás: vivirás.' },
    { c: 'future-reg', s: 'Nosotros{we} ___ la{the|f} cena{dinner|f} esta{this|f} noche{night|f}.', base: 'preparar', gloss: 'to prepare', a: ['prepararemos'], p: 'nosotros', en: 'We will prepare dinner tonight.', why: 'Nosotros is the only form without an accent: prepararemos.' },
    { c: 'future-reg', s: 'Este{this|m} invierno{winter|m} ___ mucho{a lot} en{in} la{the|f} montaña{mountains|f}.', base: 'nevar', hint: 'it', gloss: 'to snow', a: ['nevará'], p: 'él', en: 'This winter it will snow a lot in the mountains.', why: 'A prediction: futuro simple. Nevar is regular here, even though it changes stem in the present (nieva).' },
    { c: 'future-reg', s: 'Algún_día{one day|m} ___ una{a|f} casa{house|f} junto_al{by the|m} mar{sea|m}.', base: 'comprar', hint: 'yo', gloss: 'to buy', a: ['compraré'], p: 'yo', en: 'One day I will buy a house by the sea.', why: 'Algún día is a distant, uncertain future: compraré.' },
    { c: 'future-reg', s: '¿Ustedes{you (plural)} ___ a{to} la{the|f} boda{wedding|f} de{of} Carmen{Carmen}?', base: 'ir', gloss: 'to go', a: ['irán'], p: 'ellos', en: 'Will you go to Carmen’s wedding?', why: 'Ir is regular in the futuro: ir plus -án. Ustedes takes the ellos form: irán.' },
    { c: 'future-reg', s: 'Los{the|m.pl} niños{children|m.pl} ___ mucho{a lot} en{at} el{the|m} campamento{camp|m}.', base: 'aprender', gloss: 'to learn', a: ['aprenderán'], p: 'ellos', en: 'The children will learn a lot at the camp.', why: 'Ellos takes -án on the whole infinitive: aprenderán.' },
    { c: 'future-reg', s: 'Te{you} lo{it|m} ___ mañana{tomorrow}, lo_prometo{I promise}.', base: 'explicar', hint: 'yo', gloss: 'to explain', a: ['explicaré'], p: 'yo', en: 'I will explain it to you tomorrow, I promise.', why: 'A promise: futuro simple, explicaré.' },
    { c: 'future-reg', s: 'Mi{my|f} hija{daughter|f} ___ dieciocho{eighteen} años{year|m.pl} en{in} mayo{May}.', base: 'cumplir', gloss: 'to turn (an age)', a: ['cumplirá'], p: 'él', en: 'My daughter will turn eighteen in May.', why: 'Ella takes -á: cumplirá.' },
    { c: 'future-reg', s: 'Seguro_que{surely} ___ un{a|m} buen{good|m} médico{doctor|m}.', base: 'ser', hint: 'tú', gloss: 'to be', a: ['serás'], p: 'tú', en: 'You will surely be a good doctor.', why: 'Ser is regular in the futuro: serás.' },
    { c: 'future-reg', s: 'El_próximo_año{next year|m} ___ en{in} un{a|m} apartamento{apartment|m} más{more} grande{big|m}.', base: 'vivir', hint: 'nosotros', gloss: 'to live', a: ['viviremos'], p: 'nosotros', en: 'Next year we will live in a bigger apartment.', why: 'Nosotros takes -emos with no accent: viviremos.' },
    { c: 'future-reg', s: '¿Cuándo{when} ___ los{the|m.pl} resultados{result|m.pl} del{of the|m} examen{exam|m}?', base: 'recibir', hint: 'nosotros', gloss: 'to receive', a: ['recibiremos'], p: 'nosotros', en: 'When will we receive the exam results?', why: 'Nosotros: recibiremos, no accent.' },
    { c: 'future-reg', s: 'Estoy{I am} seguro{sure|m} de_que{that} todo{everything|m} ___ bien{well}.', base: 'ir', gloss: 'to go', a: ['irá'], p: 'él', en: 'I am sure everything will go well.', why: 'Ir is regular: irá, with an accent.' },
    { c: 'future-reg', s: 'Ustedes{you (plural)} ___ la{the|f} mesa{table|f} y{and} yo{I} lavaré{will wash} los{the|m.pl} platos{plate|m.pl}.', base: 'levantar', gloss: 'to clear (the table)', a: ['levantarán'], p: 'ellos', en: 'You will clear the table and I will wash the plates.', why: 'Ustedes takes the ellos form, -án: levantarán.' },

    // Futuro irregular
    { c: 'future-irr', s: 'Mañana{tomorrow} no{not} ___ venir{come} a{to} clase{class|f}.', base: 'poder', hint: 'yo', gloss: 'can, to be able to', a: ['podré'], p: 'yo', en: 'Tomorrow I won’t be able to come to class.', why: 'Poder drops the e: podr- plus -é.' },
    { c: 'future-irr', s: 'El{the|m} jefe{boss|m} nos{us} ___ la{the|f} respuesta{answer|f} el{on|m} lunes{Monday|m}.', base: 'decir', gloss: 'to tell', a: ['dirá'], p: 'él', en: 'The boss will tell us the answer on Monday.', why: 'Decir shrinks to dir-: dirá.' },
    { c: 'future-irr', s: '¿A_qué_hora{what time} ___ de{from} casa{home|f}?', base: 'salir', hint: 'tú', gloss: 'to leave', a: ['saldrás'], p: 'tú', en: 'What time will you leave home?', why: 'Salir replaces the i with d: saldr- plus -ás.' },
    { c: 'future-irr', s: 'Ellos{they|m.pl} no{not} ___ tiempo{time|m} para{to} visitarnos{visit us}.', base: 'tener', gloss: 'to have', a: ['tendrán'], p: 'ellos', en: 'They won’t have time to visit us.', why: 'Tener becomes tendr-: tendrán.' },
    { c: 'future-irr', s: '¿Qué{what} ___ ustedes{you (plural)} este{this|m} verano{summer|m}?', base: 'hacer', gloss: 'to do', a: ['harán'], p: 'ellos', en: 'What will you do this summer?', why: 'Hacer shrinks to har-. Ustedes takes the ellos form: harán.' },
    { c: 'future-irr', s: 'Mis{my|m.pl} primos{cousin|m.pl} ___ a{to} la{the|f} boda{wedding|f} desde{from} Chile{Chile}.', base: 'venir', gloss: 'to come', a: ['vendrán'], p: 'ellos', en: 'My cousins will come to the wedding from Chile.', why: 'Venir becomes vendr-: vendrán.' },
    { c: 'future-irr', s: 'Mañana{tomorrow} ___ un{a|m} concierto{concert|m} en{in} la{the|f} plaza{square|f}.', base: 'haber', hint: 'hay', gloss: 'there is (hay)', a: ['habrá'], p: 'él', en: 'Tomorrow there will be a concert in the square.', why: 'Hay in the future is habrá, one form.' },
    { c: 'future-irr', s: 'Te{you} ___ el{the|m} café{coffee|m} en{on} la{the|f} mesa{table|f}.', base: 'poner', hint: 'yo', gloss: 'to put', a: ['pondré'], p: 'yo', en: 'I will put your coffee on the table.', why: 'Poner becomes pondr-: pondré.' },
    { c: 'future-irr', s: 'Pronto{soon} ___ la{the|f} verdad{truth|f}.', base: 'saber', hint: 'nosotros', gloss: 'to know', a: ['sabremos'], p: 'nosotros', en: 'Soon we will know the truth.', why: 'Saber drops the e: sabr- plus -emos, no accent.' },
    { c: 'future-irr', s: 'Seguro_que{surely} él{he|m} no{not} ___ venir{come} con{with} nosotros{us}.', base: 'querer', gloss: 'to want', a: ['querrá'], p: 'él', en: 'He surely won’t want to come with us.', why: 'Querer drops the e and doubles the r: querrá.' },
    { c: 'future-irr', s: 'Hoy{today} ___ mucho{a lot of|m} calor{heat|m}, según{according to} las{the|f.pl} noticias{news|f.pl}.', base: 'hacer', hint: 'it', gloss: 'to be (weather)', a: ['hará'], p: 'él', en: 'It will be very hot today, according to the news.', why: 'A forecast: futuro simple. Hacer shortens to har-: hará.' },
    { c: 'future-irr', s: 'Esta{this|f} casa{house|f} ___ mucho{a lot} dentro_de{in} unos{a few|m.pl} años{year|m.pl}.', base: 'valer', gloss: 'to be worth', a: ['valdrá'], p: 'él', en: 'This house will be worth a lot in a few years.', why: 'Valer becomes valdr-: valdrá.' },
    { c: 'future-irr', s: 'No{not} ___ todos{all|m.pl} en{in} el{the|m} carro{car|m}.', base: 'caber', hint: 'nosotros', gloss: 'to fit', a: ['cabremos'], p: 'nosotros', en: 'We won’t all fit in the car.', why: 'Caber drops the e: cabr- plus -emos.' },
    { c: 'future-irr', s: '¿Cuándo{when} ___ las{the|f.pl} notas{grade|f.pl}?', base: 'poner', hint: 'ellos', gloss: 'to put (up)', a: ['pondrán'], p: 'ellos', en: 'When will they put up the grades?', why: 'Poner becomes pondr-: pondrán.' },
    { c: 'future-irr', s: '¿Ustedes{you (plural)} ___ venir{come} a{to} la{the|f} cena{dinner|f} del{on|m} sábado{Saturday|m}?', base: 'poder', gloss: 'can, to be able to', a: ['podrán'], p: 'ellos', en: 'Will you be able to come to the dinner on Saturday?', why: 'Poder drops the e: podr-. Ustedes takes the ellos form: podrán.' },
    { c: 'future-irr', s: 'Yo{I} ___ lo_que{what} pienso{I think} en{at} la{the|f} reunión{meeting|f}.', base: 'decir', gloss: 'to say', a: ['diré'], p: 'yo', en: 'I will say what I think at the meeting.', why: 'Decir shrinks to dir-: diré.' },
    { c: 'future-irr', s: 'Mi{my|f} hermana{sister|f} ___ de{on} viaje{trip|m} el{on|m} domingo{Sunday|m}.', base: 'salir', gloss: 'to set off', a: ['saldrá'], p: 'él', en: 'My sister will set off on a trip on Sunday.', why: 'Salir becomes saldr-: saldrá.' },
    { c: 'future-irr', s: 'Creo{I think} que{that} el{the|m} paquete{parcel|m} no{not} ___ en{in} el{the|m} buzón{letterbox|m}.', base: 'caber', gloss: 'to fit', a: ['cabrá'], p: 'él', en: 'I think the parcel won’t fit in the letterbox.', why: 'Caber drops the e: cabrá.' },

    // Probabilidad y futuro perfecto
    { c: 'future-prob', s: 'No{not} sé{I know} qué{what} hora{time|f} es{it is}. ___ las{the|f.pl} siete{seven}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['Serán'], p: 'ellos', en: 'I don’t know what time it is. It must be about seven.', why: 'A guess about the present takes the futuro simple: serán las siete.' },
    { c: 'future-prob', s: '¿Dónde{where} ___ mis{my|m.pl} lentes{glasses|m.pl}?', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estarán'], p: 'ellos', en: 'Where can my glasses be?', why: 'Wondering about the present: estarán, I wonder where they are.' },
    { c: 'future-prob', s: 'Esa{that|f} chica{girl|f} ___ unos{about|m.pl} veinte{twenty} años{year|m.pl}.', base: 'tener', hint: 'guess', gloss: 'to have', a: ['tendrá'], p: 'él', en: 'That girl must be about twenty.', why: 'An estimate of age: tendrá, she must be.' },
    { c: 'future-prob', s: 'Ana{Ana} no{not} contesta{answers}. ___ el{the|m} celular{cell phone|m} en{at} casa{home|f}.', base: 'dejar', hint: 'guess, perf.', gloss: 'to leave', a: ['Habrá dejado'], p: 'él', en: 'Ana isn’t answering. She must have left her phone at home.', why: 'A guess about something that already happened: futuro perfecto, habrá dejado.' },
    { c: 'future-prob', s: 'Para{by} el{the|m} viernes{Friday|m} ___ el{the|m} informe{report|m}.', base: 'terminar', hint: 'yo, perfecto', gloss: 'to finish', a: ['habré terminado'], p: 'yo', en: 'By Friday I will have finished the report.', why: 'Finished by a point in the future: futuro perfecto, habré terminado.' },
    { c: 'future-prob', s: 'Cuando{when} llegues{you arrive}, nosotros{we} ya{already} ___.', base: 'cenar', hint: 'perfecto', gloss: 'to have dinner', a: ['habremos cenado'], p: 'nosotros', en: 'When you arrive, we will already have had dinner.', why: 'Done before a future moment: habremos cenado.' },
    { c: 'future-prob', s: '¿Quién{who} ___ a{at} estas{these|f.pl} horas{hour|f.pl}?', base: 'ser', hint: 'guess', gloss: 'to be', a: ['será'], p: 'él', en: 'Who can that be at this hour?', why: 'Someone is at the door and you wonder who: será.' },
    { c: 'future-prob', s: 'Los{the|m.pl} niños{children|m.pl} ___ hambre{hunger|f}, no{not} han{have} comido{eaten} nada{anything}.', base: 'tener', hint: 'guess', gloss: 'to have', a: ['tendrán'], p: 'ellos', en: 'The children must be hungry, they haven’t eaten anything.', why: 'A guess about now: tendrán hambre, they must be hungry.' },
    { c: 'future-prob', s: 'El{the|m} tren{train|m} ya{already} ___, son{it is} las{the|f.pl} nueve{nine} y{and} media{half}.', base: 'salir', hint: 'guess, perf.', gloss: 'to leave', a: ['habrá salido'], p: 'él', en: 'The train must have left already, it is half past nine.', why: 'A guess about the recent past: futuro perfecto, habrá salido.' },
    { c: 'future-prob', s: '¿Por_qué{why} no{not} viene{comes} Luis{Luis}? ___ mucho{a lot of|m} tráfico{traffic|m}.', base: 'haber', hint: 'hay, guess', gloss: 'there is (hay)', a: ['Habrá'], p: 'él', en: 'Why isn’t Luis coming? There must be a lot of traffic.', why: 'A guess with hay: habrá mucho tráfico, there is probably a lot of traffic.' },
    { c: 'future-prob', s: 'Dentro_de{in} un{a|m} año{year|m} ___ la{the|f} carrera{degree|f}.', base: 'terminar', hint: 'tú, perfecto', gloss: 'to finish', a: ['habrás terminado'], p: 'tú', en: 'In a year you will have finished your degree.', why: 'Finished by a future point: habrás terminado.' },
    { c: 'future-prob', s: '¿Ustedes{you (plural)} ___ la{the|f} casa{house|f} antes_de{before} septiembre{September}?', base: 'vender', hint: 'perfecto', gloss: 'to sell', a: ['habrán vendido'], p: 'ellos', en: 'Will you have sold the house before September?', why: 'Antes de septiembre sets the deadline. Ustedes takes the ellos form: habrán vendido.' },
    { c: 'future-prob', s: 'Mi{my|m} vecino{neighbour|m} ___ en{in} el{the|m} extranjero{abroad|m}, habla{he speaks} cuatro{four} idiomas{language|m.pl}.', base: 'vivir', hint: 'guess, perf.', gloss: 'to live', a: ['habrá vivido'], p: 'él', en: 'My neighbour must have lived abroad, he speaks four languages.', why: 'A guess about his past from what you see now: habrá vivido.' },
    { c: 'future-prob', s: 'Marta{Marta} no{not} está{is} en{at} casa{home|f}. ___ en{at} el{the|m} trabajo{work|m}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['Estará'], p: 'él', en: 'Marta isn’t at home. She must be at work.', why: 'A guess about where she is now: estará.' },
    { c: 'future-prob', s: 'Para{by} el{the|m} año{year|m} 2040{2040} los{the|m.pl} carros{car|m.pl} ___ mucho{a lot}.', base: 'cambiar', hint: 'ellos, perf.', gloss: 'to change', a: ['habrán cambiado'], p: 'ellos', en: 'By the year 2040 cars will have changed a lot.', why: 'Para el año 2040 sets a future point: habrán cambiado.' },
    { c: 'future-prob', s: 'Son{it is} las{the|f.pl} once{eleven}. Los{the|m.pl} niños{children|m.pl} ya{already} ___.', base: 'dormirse', hint: 'guess, perf.', gloss: 'to fall asleep', a: ['se habrán dormido'], p: 'ellos', en: 'It is eleven. The children must have fallen asleep by now.', why: 'A guess about the recent past: se habrán dormido, with the pronoun before habrán.' },

    // Ir a o futuro
    { c: 'future-choice', s: 'Este{this|m} fin_de_semana{weekend|m} ___ a{(personal a)} mis{my|m.pl} padres{parents|m.pl}.', base: 'visitar', hint: 'yo, ir a', gloss: 'to visit', a: ['voy a visitar', 'visitaré'], p: 'yo', en: 'This weekend I am going to visit my parents.', why: 'A plan already made: ir a is the natural choice, voy a visitar. Visitaré is correct too but sounds more formal.' },
    { c: 'future-choice', s: 'Tranquila{don’t worry|f}, yo{I} te{you} ___ con{with} la{the|f} mudanza{move|f}.', base: 'ayudar', hint: 'futuro', gloss: 'to help', a: ['ayudaré', 'voy a ayudar'], p: 'yo', en: 'Don’t worry, I will help you with the move.', why: 'A promise: futuro simple, ayudaré. Te voy a ayudar is also heard.' },
    { c: 'future-choice', s: 'Mira{look}, el{the|m} niño{child|m} ___.', base: 'caerse', hint: 'ir a', gloss: 'to fall', a: ['se va a caer', 'va a caerse'], p: 'él', en: 'Look, the child is going to fall.', why: 'Evidence right in front of you: only ir a sounds natural. Se caerá would be a prediction with no clear evidence.' },
    { c: 'future-choice', s: 'Dentro_de{in} cincuenta{fifty} años{year|m.pl} la{the|f} gente{people|f} ___ en{on} Marte{Mars}.', base: 'vivir', hint: 'futuro', gloss: 'to live', a: ['vivirá', 'va a vivir'], p: 'él', en: 'In fifty years people will live on Mars.', why: 'A distant prediction: vivirá. Va a vivir is possible but less usual so far ahead. Gente is singular.' },
    { c: 'future-choice', s: 'Esta{this|f} noche{night|f} nosotros{we} ___ en{at} casa{home|f}.', base: 'quedarse', hint: 'ir a', gloss: 'to stay', a: ['nos vamos a quedar', 'vamos a quedarnos', 'nos quedaremos'], p: 'nosotros', en: 'Tonight we are going to stay at home.', why: 'A plan for tonight: ir a, with the pronoun before vamos or attached: nos vamos a quedar, vamos a quedarnos.' },
    { c: 'future-choice', s: '¿Qué{what} ___ ustedes{you (plural)} después_de{after} la{the|f} universidad{university|f}?', base: 'hacer', hint: 'ir a', gloss: 'to do', a: ['van a hacer', 'harán'], p: 'ellos', en: 'What are you going to do after university?', why: 'Asking about plans: van a hacer. Harán is fine too. Ustedes takes the ellos form.' },
    { c: 'future-choice', s: 'No{not} sé{I know} qué{what} hora{time|f} es{it is}, ___ las{the|f.pl} nueve{nine}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['serán'], p: 'ellos', en: 'I don’t know what time it is, it must be about nine.', why: 'A guess about the present takes the futuro simple only: serán las nueve.' },
    { c: 'future-choice', s: 'Te{you} lo{it|m} ___ mañana{tomorrow} sin_falta{without fail}.', base: 'devolver', hint: 'yo, futuro', gloss: 'to give back', a: ['devolveré', 'voy a devolver'], p: 'yo', en: 'I will give it back to you tomorrow without fail.', why: 'A promise: devolveré. In speech te lo voy a devolver is just as common.' },
    { c: 'future-choice', s: 'El{the|m} próximo{next|m} verano{summer|m} mis{my|m.pl} amigos{friend|m.pl} ___ un{a|m} viaje{trip|m} a{to} Japón{Japan}.', base: 'hacer', hint: 'ir a', gloss: 'to make', a: ['van a hacer', 'harán'], p: 'ellos', en: 'Next summer my friends are going to take a trip to Japan.', why: 'A plan: van a hacer. Harán works too, a little more formal.' },
    { c: 'future-choice', s: 'Ya{already} lo{it|m} tengo{I have} decidido{decided|m}: ___ este{this|m} trabajo{job|m}.', base: 'dejar', hint: 'yo, ir a', gloss: 'to leave, to quit', a: ['voy a dejar', 'dejaré'], p: 'yo', en: 'I have already decided: I am going to quit this job.', why: 'A decision already made: ir a, voy a dejar. Dejaré is possible but sounds more solemn.' },
    { c: 'future-choice', s: 'Creo{I think} que{that} mañana{tomorrow} ___ sol{sun|m}.', base: 'hacer', hint: 'it, futuro', gloss: 'to be (weather)', a: ['hará', 'va a hacer'], p: 'él', en: 'I think it will be sunny tomorrow.', why: 'A weather prediction: both work. Hará sol is forecast style, va a hacer sol is the everyday one.' },
    { c: 'future-choice', s: 'Cuando{when} sea{I am} mayor{older}, ___ médica{doctor|f}.', base: 'ser', hint: 'yo, futuro', gloss: 'to be', a: ['seré', 'voy a ser'], p: 'yo', en: 'When I grow up, I will be a doctor.', why: 'The distant future after cuando sea mayor: seré médica. Voy a ser is also fine.' },
    { c: 'future-choice', s: 'La_próxima_semana{next week|f} el{the|m} médico{doctor|m} me{me} ___ los{the|m.pl} resultados{result|m.pl}.', base: 'dar', hint: 'ir a', gloss: 'to give', a: ['va a dar', 'dará'], p: 'él', en: 'Next week the doctor is going to give me the results.', why: 'A fixed arrangement in the near future: va a dar. Dará is equally correct.' },
    { c: 'future-choice', s: 'Tú{you} ___ tarde{late} otra_vez{again}, seguro{for sure}.', base: 'llegar', hint: 'futuro', gloss: 'to arrive', a: ['llegarás', 'vas a llegar'], p: 'tú', en: 'You will be late again, for sure.', why: 'A prediction from what you know of the person: llegarás. Vas a llegar works as well.' },
    { c: 'future-choice', s: 'Mañana{tomorrow} ___ temprano{early} para{to} tomar{catch} el{the|m} tren{train|m}.', base: 'levantarse', hint: 'yo, ir a', gloss: 'to get up', a: ['me voy a levantar', 'voy a levantarme', 'me levantaré'], p: 'yo', en: 'Tomorrow I am going to get up early to catch the train.', why: 'A plan: ir a, with the pronoun before voy or attached. Me levantaré is also correct.' },
    { c: 'future-choice', s: 'Los{the|m.pl} científicos{scientist|m.pl} ___ una{a|f} cura{cure|f} algún_día{one day|m}.', base: 'encontrar', hint: 'futuro', gloss: 'to find', a: ['encontrarán', 'van a encontrar'], p: 'ellos', en: 'Scientists will find a cure one day.', why: 'Algún día is the distant, uncertain future: encontrarán. Van a encontrar is possible but less usual here.' },
  ],
};
